from translator import translate_line
from llm_translate import explain_with_gpt

USE_LLM = True  # Set to False to use rule-based explanations

print("💬 Code to English — type 'END' to finish input\n")

lines = []
while True:
    line = input()
    if line.strip().upper() == "END":
        break
    lines.append(line)

print("\n🧠 Translation:\n")
for i, line in enumerate(lines, 1):
    if USE_LLM:
        simple = explain_with_gpt(line)
        explanation = "Generated by GPT-4"
    else:
        simple, explanation = translate_line(line)

    print(f"{i}. {line.strip()} → {simple}")
    print(f"   Explanation: {explanation}\n")
